---
title: "Agricultural Markets"
subtitle: "Lecture 1: Preferences and Demand"
author: "David Ubilava"
date: "University of Sydney"
output:
  xaringan::moon_reader:
    css: [default, metropolis, metropolis-fonts, style.css]
    lib_dir: libs
    includes:
      after_body: insert-logo.html
    nature:
      highlightStyle: github
      countIncrementalSlides: false
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```



# Choice and Individual Demand

- A consumer at any given time faces an array of choices. These choices are linked with their *needs*. 
- Ideally, the consumer would like to satisfy all of these needs, but their choices are constrained by their disposable income - the budget allocated for purchasing goods. 
- The objective of a consumer, then, is to select a subset of goods that *best* satisfy their needs, subject to their budget constraint. 

---


# Choice and Individual Demand

- Economists define "best" in terms of consumers' attempts to maximize their *utility*. 
- Utility is an economic term describing satisfaction from the consumption of goods. 
- While it is a unit-free measure, in general, more utility is better than less utility, and positive utility is "good" and negative utility is "bad."

---


# Choice and Individual Demand

- Mathematically, for a set of goods, $\mathbf{x}=(x_1,\ldots,x_n)'$, the utility approach to the theory of demand is given by: $$\max U(\mathbf{x}),\;~~s.t.\;~\mathbf{p}'\mathbf{x} \leq M,$$ where $\mathbf{p}=(p_1,\ldots,p_n)'$ is a vector of prices for the given set of goods, and $M$ is the total disposable income (i.e., the budget). 
- Thus, a consumer tries to attain the maximum utility they can afford, given their income and the prices of goods.

---


# Choice and Individual Demand

- Market determines prices of goods - i.e., a consumer has no control over the prices. Changes to prices affect a consumer's decision-making. 
- A consumer can afford and, thus, will purchase more of the same good as the price of the good drops. This is known as the *substitution effect*. 
- The substitution effect is always inversely related to the price change. 

---


# Choice and Individual Demand

- A decrease in price of a good, in effect, is equivalent to an increase in income - a consumer can afford more of all goods with the same amount of money. This is known as the *income effect*. 
- The income effect, usually (but not necessarily), is inversely related to the price change. 
- Thus, a price drop will typically increase the quantity demanded due to the income effect as well as the substitution effect. 

---


# Choice and Individual Demand

- For some goods, real income and demand are inversely related. This is equivalent to the negative income effect due to price decrease. 
- Such goods are called *inferior goods*. 
- For inferior goods, the income and the substitution effects have opposite signs.
- In most instances, the expenditure share of a good is a small fraction of the disposable income; thus, the substitution effect typically dominates the income effect.

---


# Choice and Individual Demand

- At the extreme, the income effect might outweigh the substitution effect, resulting in a positively sloped demand curve. 
- This is known as *Giffen's paradox*, and such goods are referred to as the *Giffen goods*. 
- It might occur, for example, when a staple commodity, such as rice, constitutes a large portion of consumer's expenditures. 
- By the same token, if the income effect outweighs the substitution effect, we might observe a negative relationship between the demand for product $i$ and the change in price of product $j$, even when the two are substitutes. 

---


# Market Demand

- We obtain aggregate or market demand when we add up (horizontally) individual consumer demand functions. 
- Market demand is a schedule of product quantities that all consumers in a market are willing to purchase at given prices, everything else held constant. 
- Normally, the demand curve is downward sloping, which is inferred in the *law of demand*.

---


# Market Demand

- Own price of the good is a sole factor affecting the quantity demanded, which results in *movement along the demand curve*. 

- All other factors may influence demand by *shifting the demand curve*. 

- These factors can be:
  * economic (e.g., prices and availability of other goods and services, income and its distribution); 
  * demographic (population size and its distribution by age, gender, ethnicity, etc.); 
  * tastes and preferences (influenced by information and advertising, lifestyle, etc.).

---


# Demand Elasticities

## Price Elasticities of Demand

- The responsiveness of quantity demanded to a price change - known as the own-price elasticity of demand (demand elasticity) - may vary from product to product, over time, and across locations. For example:
  * quantity of salt purchased will not vary greatly due to the price change, but quantity of bananas purchased will likely be more responsive to price changes. From the consumers' standpoint: bananas have substitutes, but salt doesn't. 
  * quantity of rice purchased is likely to be less responsive to price changes in Asian countries, where it is considered a staple food, than in the Western world, where rice is viewed more as a side dish, perhaps with more substitutes.

---


# Demand Elasticities

## Price Elasticities of Demand

- Mathematically, price elasticity is given by: $$\epsilon = \frac{\partial Q}{Q}/\frac{\partial P}{P},$$ where $\partial$ denotes an infinitesimal change. Note that $\frac{\partial X}{X} \equiv \%\Delta X$, and so price elasticity is defined as the percentage change in quantity relative to the percentage change in price. 
- That the elasticity is measured in relative (or percentage) terms, makes it an attractive measure as it facilitates a direct comparison between goods with possibly different units of measurement of quantities and prices. 

---


# Demand Elasticities

## Price Elasticities of Demand

- The foregoing equation can be rewritten as: $$\epsilon = \frac{\partial Q}{\partial P}\frac{P}{Q},$$ where $\frac{\partial Q}{\partial P}$ is the slope of the demand curve. 
- Because of the downward-sloping demand curve, the price elasticity measure will necessarily be negative. The magnitude of the elasticity measure helps us differentiate between *inelastic*, $|\epsilon_{ii}| < 1$, and *elastic*, $|\epsilon_{ii}| > 1$, segments of the demand curve, with $|\epsilon_{ii}| = 1$ representing the *unit-elastic* case.

---


# Demand Elasticities

## Price Elasticities of Demand

- For most functional forms, including the linear demand, the elasticity coefficient varies along the demand curve. 
- Exceptions are if demand is represented by a straight horizontal line, a straight vertical line, a power function, and a rectangular hyperbola. 
- In general, demand for different goods is usually categorized as elastic or inelastic.

---


# Demand Elasticities

## Price Elasticities of Demand

- The responsiveness of the demand for a good $i$ to a price changes of a related good $j$ is known as the cross-price elasticity of demand (cross-price elasticity). 
- Mathematically, cross-price elasticity is given by: $$\epsilon_{ij} = \frac{\partial Q_i}{Q_i}/\frac{\partial P_j}{P_j},$$ or, alternatively: $$\epsilon_{ij} = \frac{\partial Q_i}{\partial P_j}\frac{P_j}{Q_i}$$

---


# Demand Elasticities

## Price Elasticities of Demand

- Three types of relationships - which are related to the substitution effect - can be identified depending on the sign of cross-price elasticity: substitute goods, $\epsilon_{ij} > 0$; complement goods, $\epsilon_{ij} < 0$; and independent goods, $\epsilon_{ij} = 0$.

---


# Demand Elasticities

## Income Elasticity of Demand

- The responsiveness of the demand for a good to income changes is income elasticity of demand (income elasticity). 
- Mathematically, income elasticity is given by: $$\epsilon_{m} = \frac{\partial Q}{Q}/\frac{\partial M}{M},$$ or, alternatively: $$\epsilon_{m} = \frac{\partial Q}{\partial M}\frac{M}{Q}$$

---


# Demand Elasticities

## Income Elasticity of Demand

- Three types of goods can be identified based on the sign and magnitude of income elasticity. These are normal goods, $0 \le \epsilon_{m} \le 1$; superior goods, $\epsilon_{m} > 1$; and inferior goods, $\epsilon_{m} < 0$.

---


# Demand Elasticities

## Income Elasticity of Demand

- Typically, the income elasticity of demand has a positive value: as income increases, consumers tend to buy more of most products. 
- However, income elasticities tend to decline as incomes increase. 
- As a consequence, for a very low-income country, the income elasticity of demand for food as a whole is around 0.8, while for a very high-income country it is around 0.1. 
- This difference in income elasticities means that changes to income have a much larger relative impact on food demand in low-income countries than in high-income countries.

---


# Demand Elasticities

## Income Elasticity of Demand

- By necessity, poor people have no choice but to spend the large share of their income on food, at times as much as 80 percen; and when their incomes rise, they buy more food. 
- Eventually, however, as income increases, people start spending it on other items. 
- People spending a smaller share of income on food, as their income increases, is known as *Engel's law*.

---


# Demand Elasticities

## Income Elasticity of Demand

- Rising incomes lead people to consume more total calories, and also to consume more expensive foods. 
- These foods are often more highly processed, and include more animal products as well as more fruits and vegetables. 
- The transition in consumption from a few inexpensive starchy staples to the greater variety of more expensive foods is known as *Bennett's law*. 
- Such transition does not necessariy decrease demand for cereal grains, however. While consumers reduce their direct consumption of cereal grains as food, they increase the total usage of cereal grains as animal feed.

---


# Readings

Tomek & Kaiser, Chapters 2 & 3

Norton, Alwang & Masters, Chapter 3
