---
title: "Agricultural Markets"
subtitle: "Lecture 9: Price Discovery"
author: "David Ubilava"
date: "University of Sydney"
output:
  xaringan::moon_reader:
    css: [default, metropolis, metropolis-fonts, style.css]
    lib_dir: libs
    nature:
      highlightStyle: github
      countIncrementalSlides: false
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```



# Pricing Mechanisms

- Within a given market structure, prices are established or 'discovered' by means of institutional mechanisms and arrangements that facilitate the interaction between buyers and sellers.
- In a perfect market, all participants have access to the same information at no cost, and hence prices reflect the existing economic conditions. As new information arrives, prices change instantly to a new equilibrium (efficient market hypothesis). 

---


# Pricing Mechanisms

- Pricing mechanisms can influence the costs of price discovery, and therefore prices, at least indirectly though outcomes they generate.
- Three broad categories of pricing mechanisms include:
  * negotiation - a bargaining process that may be formal or informal;
  * auctions - some type of bidding performed in a structured setting;
  * administering - price-setting of some sort.

---


# Negotiated Prices

- An informal negotiation between the involved parties is not uncommon, as it is potentially the least-cost method  of price discovery for locally marketed commodities of varying quality. 
- A formal negotiation typically involves a union, a cooperative of farmers, who negotiate the terms of sales on behalf of individuals they represent. Such negotiation takes a structured bargaining form, and if successful, results in a contract for a specific time period that details benefits and responsibilities. 

---


# Auctions

- Auctions represent a structured framework for bidding, using clearly defined rules.
- An ascending bid auction, better known as the 'English auction' is one of the most common types of auctions. The auction starts at some reservation price, and is complete once no-one is willing to bid higher than the most recent bid. Such auction, typically, leads to over-bidding - a phenomenon referred to as the 'winner's curse.'

---

# Auctions

- Another popular type of auction is descending bid auction, better known as the 'Dutch auction.' The auction starts at some reasonably high price, presumably such that no-one is willing to bid. The auctioneer then lowers the ask price by some increments until someone bids, at which point the auction completes. 
- One other popular type of auction is the sealed-bid auction, and its variant the second-price sealed bid auction, also referred to as the 'Vickery auction.' The seller accepts sealed bids; the highest bid wins but pays the price of the second highest bid.

---


# Auctions

- Auctions help discover prices efficiently in instances when there is no asymmetry of information among sellers and buyers, the traded good is homogeneous, and transaction costs are negligibly small.
- To that end, centralized auctions have declined for agricultural commodities where the costs of transportation, storage, and handling are considerable; local auctions remain relevant, however, as they are a convenient (least costly) site for selling livestock, for example.

---


# Administered Prices

- Administered prices are set&mdash;administered&mdash;by government via a regulation or policy, or by a firm's management. 
- In setting prices, decision makers are influenced by economic factors. But prices are, ultimately, decided by the decision makers' interpretation of market conditions rather than by negotiation or auctions.
- Such mechanism, in certain circumstances (e.g., prices in retail stores), is the least costly mechanism.
- In any case, for prices do be administered, the price setting entity (firm or government) should possess some power over a market.

---


# Evolution of Pricing Mechanisms

- The same commodity may be priced via different arrangements. 
- As the economies evolve, so do the pricing mechanisms.
- Indeed, pricing mechanisms evolve to minimize transactions costs (broadly defined). 
- As a result, while negotiations, auctions, and administered pricing mechanisms remain three main institutional tools for price discovery, the outcomes of these processes alter.

---


# Readings

Tomek & Kaiser, Chapter 11


