---
title: "Agricultural Markets"
subtitle: "Lecture 4: Market Integration and Trade"
author: "David Ubilava"
date: "University of Sydney"
output:
  xaringan::moon_reader:
    css: [default, metropolis, metropolis-fonts, style.css]
    lib_dir: libs
    nature:
      highlightStyle: github
      countIncrementalSlides: false
header-includes: 
  - \usepackage{tikz}
  - \usepackage{pgfplots}
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```


# Spatial Market Integration

- Agricultural commodities typically are produced in geographically diverse locations, and can be costly to transport.
- Relationships among geographically distant (or spatially separated) markets are often examined by comparing prices in these markets.

---


# Spatial Market Integration

- To the extent that supply and demand forces differ across markets, prices of agricultural commodities can (and do) vary spatially. 
- Given a competitive market structure, spatial price relationships are determined by *transfer costs* among markets. 
- While transportation is one of the key determinants of the transfer costs, its other important components may include costs related to contracting, insurance, financing, etc.

---


# Spatial Market Integration

- Spatial arbitrage, through the actions of economic agents, ensures that the price differential between regions $i$ and $j$, $p_{jt}-p_{it}$ at any given time, $t$, does not exceed the transfer costs, $\tau_{ijt}$: $$p_{jt}-p_{it} \le \tau_{ijt}.$$ This is referred to as *long--run competitive equilibrium*. 
- The condition will hold as an equality if the two regions engage in a trade with each other, thereby exhausting the rents to spatial arbitrage. 
- That is, when trade occurs, price differentials should move one-for-one with the costs of spatial arbitrage; otherwise, there may be no correlation among market prices even though the competitive equilibrium holds. 

---


# Spatial Market Integration

- *Market integration*, defined as tradability or contestability between markets, is a (related but) slightly different concept from competitive spatial equilibrium. 
- Market integration implies the transfer of excess demand from one market to another, manifest in the physical flow of commodity, the transmission of price shocks from one market to another, or both. 

---


# The Law of One Price

- Two spatially separated markets: 
  * can be *in equilibrium* but not necessarily *integrated* (e.g., when the spatial arbitrage condition is satisfied but no trade occurs); 
  * can be *integrated* but not necessarily *in equilibrium* (e.g., when trade occurs but the rents to spatial arbitrage are not exhausted). 
- When both conditions are met, the *law of one price* (LOP) holds. 

---


# The Law of One Price

- The LOP suggests that, abstracting from transfer costs, regional markets that are linked by trade and arbitrage, will have a common, or unique price. 
- While the LOP (in its strong form) rarely holds in practice, there is evidence for LOP in empirical literature that explicitly accounts for transactions costs, or that explicitly focuses on traded rather than non-traded commodities.

---


# The Law of One Price

- Key to the LOP is the notion of *efficient markets*. 
- Efficiency is meant to imply that the allocation of resources is such that aggregate welfare cannot be further improved by reallocating of resources. 
- In the context of spatial arbitrage, market efficiency implies that no opportunities for profits have been left unexploited by arbitrageurs. That is, the efficient market hypothesis assumes away profitable arbitrage opportunities. 

---


# The Law of One Price

- Several caveats are in order:
  * price co-movement between two regions can arise for reasons other than those that link these regions via trade; 
  * prices that satisfy the LOP may not move together, if transfer costs are large and volatile;
  * it is not necessary for two regions to be direct trading partners for an integration to be present. As long as these regions are part of a common trading network, they may be integrated just as strongly as if they were direct trading partners. 

---


# The Law of One Price

- Several important implications follow: 
  * because trade will only occur when the price differential equals or exceeds the transfer cost, shocks to production or consumption may result in discontinuous trade flows over time;
  * to the extent that trade takes place, the price differential will remain the same (and be equal to the transfer cost);
  * integrated markets will be characterized by the simultaneous determination of prices, trade, and storage.

---


# Structure of Prices

- The LOP may not apply if buyers have less than perfect information about where to find the lowest price commodity; nor may they apply across international borders, because some goods are not transferable. 
- These principles facilitate the so-called *structure of prices* - a function of the pattern of trade and transfer costs between the trading regions. 

```{tikz structure, out.width='80%', fig.asp=0.6, dpi=200, fig.align='center', echo=FALSE, warning=FALSE, cache=TRUE}
\definecolor{indianred}{rgb}{0.80,0.36,0.36}
\definecolor{steelblue}{rgb}{0.27,0.51,0.71}
\begin{tikzpicture}[scale=1]
\draw[thick,dashed] (0,3) node[left] {$X$} -- (1,1) node[below] {$A$} -- (8,1) node[right] {$Y$} -- (5,4) node[above] {$B$} -- (0,3) -- (8,1);
\draw (-0.5,3) node[steelblue,left] {$\$3.00$} (1,.5) node[steelblue,below] {$\$2.90$} (8.5,1) node[steelblue,right] {$\$3.30$} (5,4.5) node[steelblue,above] {$\$3.10$};
\draw (0.5,2) node[indianred,below left] {$\$0.10$} (4.5,1.0) node[indianred,below] {$\$0.40$} (6.5,2.5) node[indianred,above right] {$\$0.20$} (3.0,3.5) node[indianred,above left] {$\$0.30$} (3.5,2) node[indianred,above right] {$\$0.50$};
\end{tikzpicture}
```

---


# Structure of Prices

- Implications of the structure of prices are that: 
  * the lowest-cost source determines the price in each deficit market; 
  * producers sell in whichever market yields the highest net return; 
  * the price prevailing in each surplus producing area is the deficit market price less the cost of transferring a product to that market. 
- Of course, the foregoing assumes a competitive market structure, with a homogeneous commodity, informed traders, and no barriers to trade. 

---

# Why Countries Trade

- Most economists agree that trade is, usually, helpful for successful economics development. 
- They also agree that trade generates both gainers and losers, and that some of these gains and losses may be permanent for those involved, particularly when trade is accompanied by technological change.

---

# Why Countries Trade

- Trade facilitates development because it helps a country obtain greater benefits from its productive resources by exporting what it can produce relatively more efficiently, and importing what it cannot produce, at least not as efficiently as other countries.
- Most countries export and import specific sets of goods year after year, but in agriculture, due to its seasonality and dependence on weather, there can be considerable fluctuations in quantities traded as well as the direction of the trade.

---


# Gains from Trade

- Countries trade:
  * because some can produce certain commodities when others cannot (*absolute advantage*), or, 
  * more typically, because some can produce certain commodities more efficiently than others (*comparative advantage*). 
- Gains from trade can be grouped into two categories: gains from exchange, and gains from specialization.

---

# Gains from Trade

## Gains from exchange

- Drawing supplies from a world market allows access to a wider array of products at lower cost and perhaps with greater security of supply than can be produced by domestic industries. 
- Lower prices from imported goods allow consumers to buy more goods from disposable income. 
- Lower prices for imported raw materials, that are used to produce final goods, also benefit consumers by lowering prices of these final goods. 

---


# Gains from Trade

## Gains from specialization

- Trade stimulates the expansion of low cost industries (and forces the contraction of high cost industries). 
- Increase of the size of the market allows firms or industry to take advantage of economies of scale. 
- Increase of competition provides greater emphasis on technological development and innovation, and results in increased skills of workforce.

---


# Gains from Trade

- When trade occurs, in absence of transfer costs, the intersection of the excess demand and excess supply curves yields the world price. 
- A more realistic scenario is trade with transfer costs. A way to think of the effect of transfer costs is by incorporating them into the supply function of the exporting country.
- Transfer costs increase the price at which commodities are traded, and reduce the quantity of traded commodities. As a result, in an importing market, consumers receive less of the commodity for a higher price, and producers sell more of the commodity for a higher price; the opposite is true in an exporting market.

---

# Readings

Tomek & Kaiser, Chapter 8

Norton, Alwang & Masters, Chapter 16
