---
title: "Agricultural Markets"
subtitle: "Lecture 8: Trade Policy"
author: "David Ubilava"
date: "University of Sydney"
output:
  xaringan::moon_reader:
    css: [default, metropolis, metropolis-fonts, style.css]
    lib_dir: libs
    nature:
      highlightStyle: github
      countIncrementalSlides: false
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```



# Free Trade vs Protectionism

- The case for free trade is that producers and consumers allocate resources most efficiently when governments do not distort market prices through trade policy. 
- Economic welfare of a small country is highest with free trade. 
- With restricted trade: 
  * consumers pay higher prices (than they would have paid otherwise);
  * distorted prices cause overproduction either by existing firms producing more or by more firms entering the market. 

---


# Free Trade vs Protectionismsm

- Protectionism consists of a set of actions that deviates the trade patterns from what would have been their state in absence of any regulations (i.e., in a free trade regime). 
- The case for protectionism is primarily directed to maintain a considerable degree of self-sufficiency in the country, but can also be 're-active' to ongoing economic or political processes. 
- Common levers for trade restriction are import tariffs, export taxes, as well as trade quotas. Other government interventions, e.g., production subsidies, ad-valorem taxes etc., can also distort trade, albeit to a lesser extent than those directly directed to restrict trade.

---


# Free Trade vs Protectionism

- Strongly divergent climatic conditions around the globe, create ideal conditions for making use of comparative advantage in agricultural production. Somewhat surprisingly, agriculture has been an area where governments have been reluctant to open up domestic markets to international trade.
- While the policies vary around the world (and over time), high income countries tend to favor those that help maintain high domestic prices to support local producers, while low and middle income countries tend to keep domestic prices low to support consumers, as well as to generate revenue.

---

# The Terms of Trade

- The *terms of trade* denotes export prices in terms of import prices. 
- A large country can alter terms of trade in their favor by means of trade restrictions or other equivalent trade distortion mechanisms. 
- The welfare effect of this is nonlinear, meaning that a small tariff may lead to an increase in national welfare, but at some tariff rate, the welfare will begin to decrease as the economic efficiency loss exceeds the terms of trade gain. 
- Likewise, while an excessively high export tax that completely prohibits exports leaves a country worse off, there may exist an export tax rate that maximizes national welfare through the terms of trade. 

---


# The History of Trade Negotiations

- After the World War II, nations around the world recognized the urgent need for coordinated policy efforts in the areas of economic development, monetary policy, and international trade. 
- With that in mind, 23 nations signed a multilateral agreement regulating international trade known as the General Agreement on Tariffs and Trade (GATT) in Geneva on 30 October 1947. 
- The GATT took effect on 1 January 1948, and became the vehicle for trade negotiations for the next half century, until its successor - the World Trade Organization (WTO) was formed and took effect in 1995.

---


# The History of Trade Negotiations

- Main principles of the GATT involved: 
  * *most-favored-nation* principle, meaning that trade benefits conferred on one country should be extended unconditionally to all other member countries; 
  * *national treatment*, meaning that imports should be treated no less favorably than domestic products; and 
  * *reciprocity*, meaning that negotiations should be conducted on a reciprocal and mutually advantageous basis.

---


# The History of Trade Negotiations

- The early rounds primarily focused on negotiations on tariffs and on rules for trading blocs; the middle rounds increasingly focused on non-tariff issues. 
- Agricultural trade restrictions received relatively little attention until the *Uruguay Round*, which commenced in 1986. 
- Agricultural trade restrictions were at the heart of the *Doha Round*, also called the *Development Round*, under the WTO.

---


# Agriculture in Trade Negotiations

- The idea of replacing agricultural price support with direct payments to farmers decoupled from production dates back to the late 1950s. 
- Twelfth session of the GATT Contracting Parties selected a Panel of Experts, chaired by Gottfried Haberler, to examine the effect of agricultural protectionism, fluctuating commodity prices, and the failure of export earnings to keep pace with import demand in low and middle income countries. 

---


# Agriculture in Trade Negotiations

- The report (1958) found that there was a decline in the terms of trade for primary commodities (relative to the manufactured goods). 
- This finding accords with what later became to be known as the *Prebisch--Singer hypothesis* (though Haberler himself had particular disagreement was with the idea that there was a systematic long-term decline in the terms of trade). 

---


# Agriculture in Trade Negotiations

- The report:
  * stressed the importance of minimizing the effect of agriculture subsidies on competitiveness;   
  * recommended replacing price support with direct supplementary payments not linked with production; 
  * anticipated discussion on the so-called green box subsidies---the kind of subsidies that do not distort trade, or at most cause minimal distortion, that are government-funded (not by charging consumers higher prices), and that do not involve price support.

---


# Agriculture in Trade Negotiations

- In leading up to the 1986 negotiations, high income countries strongly resisted compromises on agriculture. 
- This opposition was subsequently neutralized by guaranteeing farmers continued support, and allowing subsidies that cause not more than minimal trade distortion in order to meet public policy aims. 

---


# Uruguay Round

- The negotiations of the Uruguay Round highlighted the disparities in the ways they envisaged trade policy among high income countries and between high income and low and middle income countries. 
- The negotiations also illustrated the diversity of interests among low and middle income countries: 
  * net exporting countries were concerned about market access and effects of export subsidies available in high income countries; 
  * net importing countries, were in addition concerned about possible rising prices in world markets, particularly for food grains.

---


# Uruguay Round

- Agreement on Agriculture, which was reached in the third and final phase of the Uruguay Round, continues to be the most substantial trade liberalization agreement in agricultural products in the history of trade negotiations. The agreement revolved around these three directions: *market access*, *export competition*, and *domestic support*.

---


# Uruguay Round

- *Market access*: to convert of all existing non-tariffs into tariff equivalents; high income countries to reduce tariffs by 36% over six years; low and middle income countries to cut tariffs by 24% over 10 years; safeguard provisions to allow importers to guard against import surges and low world prices.
- *Export competition*: export subsidies capped and subsequently reduced in both value (36%) and volume (21%). 
- *Domestic support*: reduction of the level of sector--wide (rather than product-specific) support - better known as the aggregate measurement of support - by 20% over six years for high income countries, and 13% over 10 years for low and middle income countries.

---


# Doha Round

- In a 2001 meeting in Doha, Qatar, high income countries agreed to prioritize the issue of export subsidies. 
- In a 2003 ministerial-level WTO meeting in Mexico, a group of 21 low and middle income countries requested tighter domestic support restrictions for high income countries, and more flexibility for special and differential treatment for low and middle income countries. 
- The agreement was not reached, but the meeting highlighted an important milestone in history of multilateral negotiations where the group of low and middle income countries lobbied for the mutually beneficial outcome.

---


# Doha Round

- In July 2008, Doha Round negotiations broke down over an introduction of a mechanism that would allow low income countries to impose tariffs for specific products if prices of these products were to decrease sharply, or if there were to be a surge in imports. 
- In December 2013, in restarted negotiations, a partial agreement was reached on issues such as simplifying customs procedures. 
- The agreement to relax major agricultural trade constraints was minimal, however. 

---


# Doha Round

- At the 2015 Nairobi Ministerial Conference, WTO members adopted a historic decision to eliminate agricultural export subsidies. 
- Under this decision, high income countries were to immediately eliminate export subsidies, except for several agriculture products, while low and middle income countries were given longer periods for this.
- The elimination of export subsidies will help to level the playing field for farmers around the world, particularly those in poor countries which cannot compete with rich countries that boost their exports through local support mechanisms.

---


# Readings

Norton, Alwang & Masters, Chapter 17
